0-run redo

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,11 @@
-#!/usr/bin/python3
-print("Best School")
+#!/bin/bash
+
+# Check if the $PYFILE environment variable is set
+if [ -z "$PYFILE" ]; then
+  echo "Error: The PYFILE environment variable is not set."
+  exit 1
+fi
+
+# Run the Python script specified by the $PYFILE variable
+python3 "$PYFILE"
+
