1-run_inline corrected

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,2 +1,6 @@
 #!/bin/bash
+if [ -z "$PYCODE" ]; then
+  echo "Error: The PYCODE environment variable is not set."
+  exit 1
+fi
 python3 -c "$PYCODE"
